import type { Metadata } from "next";
import "./globals.css";
import { advercase, saans } from "@/fonts/fonts";
import { Suspense } from "react";
import Cursor from "@/feature/components/cursor/Cursor";
import Navbar from "@/feature/components/Navbar/Navbar";
import SmoothScroll from "@/feature/components/smoothScroll/smoothScroll";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${advercase.variable} ${saans.variable} selection:bg-primary/70 antialiased selection:text-black`}
      >
        <SmoothScroll>
          <Cursor />
          {children}
          <Navbar />
        </SmoothScroll>
      </body>
    </html>
  );
}
