import type { Metadata } from "next";
import "./globals.css";
import { advercase, saans } from "@/fonts/fonts";
import { Suspense } from "react";
import Cursor from "@/components/cursor/Cursor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${advercase.variable} ${saans.variable} antialiased selection:bg-primary/70  selection:text-black`}
      >
        <Cursor />
        {children}
      </body>
    </html>
  );
}
